default: &default
  adapter: postgresql
  encoding: unicode
  user: postgres
  host: localhost
  password: annor0543
  port: 5432
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
development:
  <<: *default
  database: global_clinic
  
test:
  <<: *default
  database: global_clinic_test

production:
  <<: *default
  database: global_clinic_production
  username: global_clinic
  password: <%= ENV["RAILS_BUDGET_APP_DATABASE_PASSWORD"] %>