default: &default
  adapter: postgresql
  encoding: unicode
  user: postgres
  host: localhost
  password: brian
  port: 5432
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
development:
  <<: *default
  database: global
  
test:
  <<: *default
  database: global_test

production:
  <<: *default
  database: global_production
  username: global
  password: <%= ENV["RAILS_BUDGET_APP_DATABASE_PASSWORD"] %>